[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.20.0"

[[redirects]]
  from = "/feed.xml"
  to = "/atom.xml"
  status = 301

[[redirects]]
  from = "/meet/"
  to = "https://savvycal.com/tim-abell/chat"
  status = 307
