#!/bin/sh
#!/bin/sh -v
(
	while ! nc -z localhost 1111; do sleep 0.1; done # https://stackoverflow.com/questions/27599839/how-to-wait-for-an-open-port-with-netcat
	xdg-open http://localhost:1111/
) &

# depends on binary from https://github.com/getzola/zola/releases/latest on path (or whatever install is preferred)
zola serve
